### ISSUE TITLE
addon calling executables?

### ISSUE THREAD

**Issue by mgonzales71** [Twilight0/script.module.streamlink.base#2]
pretty sure your addon is calling windows executables? 

little unsettling to have cmd Windows popping up randomly and then closing quickly not knowing where and what is the source.

maybe a heads up if this is new behavior?

red flags galore and a little panic before I figured out this addon / script was the source

**Comment by Twilight0** [comment]
Thanks for bringing this matter into my attention. I also noticed this behaviour. This might be a side effect on the way streamlink works in their latest implementation as it essentially is a copy of the original with some parts stripped, especially when it comes to locale messages.
Will definitely check and provide a fix asap.

**Comment by Twilight0** [comment]
Just pushed a fix, version 2018.05.21. If you 're willing to test I will appreciate
https://github.com/Twilight0/script.module.streamlink.base/commit/4cd3cde4630ac1e90f8955f0b731c508d2fd8145

**Comment by mgonzales71** [comment]
yea - kinda freaks ya out when you see some random shell/cmd window blip open/close really fast hehe 

I just installed and did a quick test - it's one data point but worked for me.  I will have more time to check it out better later today.  thanks!

**Comment by Twilight0** [comment]
It was the _version.py module doing version checking for basic logging within the cli wrapper for Windows which is redundant in Kodi's case.

**Comment by Twilight0** [comment]
After a week or so with zero complains, I can safely say that this can be closed and mark as resolved.

**Comment by mgonzales71** [comment]
Yea I meant to get back to you but was away enjoying the Memorial Day holiday here.  I’ve not seen any other issues in playback etc.  at first I thought a change may had been made to or affected network stream caching but it turned out to be transient issue with the source or some other external factor since the issue has not returned and I saw no indication that pointed to any changes with your scripts.  

Thanks again!
