### ISSUE TITLE
Link works on Streamlink cli but not if you resolve to url and then pass to Kodi to play

### ISSUE THREAD

**Issue by kumarpranay** [Twilight0/script.module.streamlink.base#5]
----

### Checklist
- [x] This is a bug report.

I can use command line steamlink (v1.1.1) to play this video. 
http://www.zengatv.com/live/ab0bff22-99d2-11e1-85c0-123141010175.html?s=zoom 

but when I resolve using a session to a playable URL and then pass to Kodi player to play, I get errors in logs indicating that the resolved http stream url cannot be read.

The same behavior happens if the URL is passed to the service.streamlink.proxy addon and the resulting localhost proxy url is passed to Kodi to play.

### System tested on
OS MacOS 10.14.5

Kodi version:
- [x] Leia 18.1

Streamlink addon version:

<addon id="service.streamlink.proxy" name="Streamlink Proxy" version="4.1.2" provider-name="Twilight0">

<addon id="script.module.streamlink.base" name="Streamlink Library" version="2019.05.08" provider-name="Streamlink Devs, Twilight0">

### Expected / Actual behavior
The resolved URL will just play on Kodi

### Explicit stream URLs to test

1. http://www.zengatv.com/live/ab0bff22-99d2-11e1-85c0-123141010175.html?s=zoom 

### Logs
```
2019-06-06 01:03:49.135 T:4677498304   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://dbuqq908y3dcs.cloudfront.net/Live/_definst_/amlst:sweetbcha1novD160L720P/chunklist_b150000.m3u8|User-Agent="Mozilla"
2019-06-06 01:03:49.135 T:123145529495552  NOTICE: Creating InputStream
2019-06-06 01:03:49.261 T:123145529495552   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
2019-06-06 01:03:49.261 T:123145529495552   ERROR: CCurlFile::Open failed with code 403 for http://dbuqq908y3dcs.cloudfront.net/Live/_definst_/amlst:sweetbcha1novD160L720P/chunklist_b150000.m3u8:
```

**Comment by Twilight0** [comment]
The url is indeed resolved, but since we get 403 error, there could be some issue with the headers.

**Comment by Twilight0** [comment]
Did you use streamlink-tester to play the stream?

**Comment by Twilight0** [comment]
I updated streamlink tester to 1.4.2, so it should play now. New dependency with the fix is also tulip 2.3.7.
Thank you for reporting.

**Comment by kumarpranay** [comment]
Thanks for the quick response and resolution. Works now.

What was the issue with the revolved http link? I tried the following which also did not work
* Resolve original link with streamlink cli and --stream-url
* Then take the output URL and run with streamlink again and it failed.

So I assume some headers need to be passed along

**Comment by Twilight0** [comment]
The issue was on one of the libraries I use which did not pass the headers correctly. I am closing this, thanks for reporting once again.
