### ISSUE TITLE
Kodi 19 Matrix

### ISSUE THREAD

**Issue by syco** [Twilight0/script.module.streamlink.base#9]
### Checklist

- [] This is a bug report.
- [x] This is a feature request.

Hi,
is there any plans to update this for Kodi 19 Matrix?

Thanks

**Comment by Twilight0** [comment]
No, I am not planning to update this module for Kodi 19, its too much of a fuss to do so. Upstream has support only for Matrix, therefore I must rebase upon into it. So probably no Leia support thereafter.
